version: '3.7'
services:
  frontend:
    image: iamiranjbar/frontend
    container_name: jobOonJa-front
    build: ../JobOonJa-Frontend/
    ports:
      - 5000:5000

  ourDB:
    container_name: ourDB
    image: mysql:5.7.16
    environment:
      MYSQL_DATABASE: joboonja
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8000:3306
    volumes:
      - ./my-datavolume:/var/lib/mysql

  backend:
    image: iamiranjbar/backend
    container_name: jobOonJa-back
    build: .
    ports:
      - 8080:8080
    depends_on:
      - ourDB
# volumes:
#   my-datavolume:
    