version: '3.7'
services:
  frontend:
    container_name: jobOonJa-front
    restart: always
    build: ../JobOonJa-Frontend/
    ports:
      - 5000:5000
    depends_on:
      - backend

  mysql:
    container_name: ourDB
    image: mysql
    environment:
      MYSQL_DATABASE: joboonja
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - /Users/amir/Desktop:/var/lib/mysql
    restart: always

  backend:
    container_name: jobOonJa-back
    restart: always
    build: .
    ports:
          - 8080:8080
    depends_on:
      - mysql