apiVersion: apps/v1
kind: Deployment
metadata:
  name: joboonja-back-deployment
  namespace: ali-edalat-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joboonja-back
  template:
    metadata:
      labels:
        app: joboonja-back
    spec:
      containers:
        - image: quay.io/aliedalat/backend
          imagePullPolicy: Always
          name: joboonja-back
          ports:
            - containerPort: 8080
          resources:
              limits:
                memory: "300Mi"
                cpu: "300m"
              requests:
                memory: "300Mi"
                cpu: "300m"
