apiVersion: v1
kind: Service
metadata:
  name: joboonja-back
spec:
  type: NodePort
  ports:
  - port: 8080
    # protocol: TCP
    # targetPort: 8080
    nodePort: 30085
  selector:
    app: joboonja-back