apiVersion: apps/v1
kind: Deployment
metadata:
  name: joboonja-front-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joboonja-front
  template:
    metadata:
      labels:
        app: joboonja-front
    spec:
      containers:
        - image: iamiranjbar/frontend
          imagePullPolicy: Always
          name: joboonja-front
          ports:
            - containerPort: 5000
          resources:
              limits:
                memory: "111Mi"
                cpu: "111m"
              requests:
                memory: "111Mi"
                cpu: "111m"
